### ISSUE TITLE
Error importing XEX with PDB 

### ISSUE THREAD

**Issue by MagnificentS** [zeroKilo/XEXLoaderWV#16]
When loading the xex alone, the loader successfully operated. However importing xex with pdb throws an error :(

log:
`java.io.IOException
	at xexloaderwv.XEXLoaderWVLoader.load(XEXLoaderWVLoader.java:59)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

---------------------------------------------------
Build Date: 2022-Jan-25 1526 EST
Ghidra Version: 10.1.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-12.0.2.10-hotspot
JVM Version: AdoptOpenJDK 12.0.2
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-xxxxxx
`

[xex + pdb](https://drive.google.com/file/d/1j934w8Ii0liQwqpEUPMMxTqbEBZ6v4yi/view?usp=sharing)

**Comment by zeroKilo** [comment]
did you give it a path to the pdb file too? seems you havent

**Comment by MagnificentS** [comment]
![image](https://user-images.githubusercontent.com/8756646/158083174-af0ee8e2-8462-4eba-b856-ff983c47dab7.png)
I did. Even changed the location

**Comment by zeroKilo** [comment]
maybe try to use a path without spaces, maybe try to add quotes, the error says it has problems opening the file

**Comment by zeroKilo** [comment]
example:
`C:\folder\game.pdb`
so full path to file

**Comment by MagnificentS** [comment]
I tried that. No luck. Even remade the project.
The xex file loads without pdb

**Comment by zeroKilo** [comment]
well either you debug the plugin with eclipse or you have to post the files somehow, dunno how to help you. is your pdb file maybe broken?

**Comment by zeroKilo** [comment]
oh and I see you use `jdk-12.0.2.10-hotspot` maybe use a new jdk, I think I use 13 or 14 now...

**Comment by zeroKilo** [comment]
so, can this be closed? do you still have problems?

**Comment by MagnificentS** [comment]
Sorry i was ill for a while. wasnt able to check. will do so soon

**Comment by Margen67** [comment]
> Sorry i was ill for a while. wasnt able to check. will do so soon

@MagnificentS
