### ISSUE TITLE
Unable to load xex error

### ISSUE THREAD

**Issue by supernoodled** [zeroKilo/XEXLoaderWV#3]
Using JDK 12.0.2, also tried JDK 13 but same result. Ghidra 9.1.0-BETA (has the same error on 9.1.0 final too, after you rename the extension.properties to allow use of that version, but tried the beta out too to rule out any compatibility errors , same with the JDK version)

Imported a BO2 MP xex and got this error:

Error importing file: default_mp.xex
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Index 57344 out of bounds for length 57344
	at xexloaderwv.XEXLoaderWVLoader.load(XEXLoaderWVLoader.java:57)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 57344 out of bounds for length 57344
	at xexloaderwv.XEXHeader.ReadPEImage(XEXHeader.java:317)
	at xexloaderwv.XEXHeader.<init>(XEXHeader.java:90)
	at xexloaderwv.XEXLoaderWVLoader.load(XEXLoaderWVLoader.java:48)
	... 11 more

---------------------------------------------------
Build Date: 2019-Sep-23 1119 EDT
Ghidra Version: 9.1-BETA
Java Home: C:\Program Files\AdoptOpenJDK\jdk-12.0.2.10-hotspot
JVM Version: AdoptOpenJDK 12.0.2
OS: Windows 10 10.0 amd64

**Comment by supernoodled** [comment]
closed, turned out I had to decompress the xex with xextool and it worked perfectly :D
